import { SEARCH_RESULTS_BATCH_SIZE } from './app-config.js?v=20260714232323';

export function createInitialAppState() {
  return {
    works: [],
    fragments: [],
    likes: new Set(),
    bookmarks: new Set(),
    likeRecords: [],
    bookmarkRecords: [],
    readingStateRecords: [],
    exportStatus: '',
    textExportStatus: '',
    importStatus: '',
    releaseStatus: '',
    pendingImport: null,
    resetConfirmationStep: '',
    resetStatus: '',
    importWorkStatus: '',
    importSaveInProgress: false,
    importWorkNoticeTone: '',
    pendingBridgeAck: null,
    importPreview: null,
    importSheetOpen: false,
    aozoraCatalogQuery: '',
    aozoraCatalogStatus: '',
    aozoraCatalogLoading: false,
    aozoraCatalogMeta: null,
    aozoraCatalogRecords: [],
    aozoraCatalogResults: [],
    aozoraCatalogVisibleCount: SEARCH_RESULTS_BATCH_SIZE,
    searchScope: 'aozora',
    remoteImportUrl: '',
    importTextDraft: '',
    importTextLastImported: '',
    converterBaseUrl: '',
    workLoadMode: 'auto',
    readerFontScale: 1,
    readerActionStatus: '',
    readerActionStatusTone: '',
    libraryWorkActionsCleanup: null,
    workHeaderProgressCleanup: null,
    workAutoLoadCleanup: null
  };
}
